# Generated by Django 5.0 on 2024-01-04 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hm_api", "0003_posts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="posts",
            old_name="username",
            new_name="user",
        ),
    ]
